---
title: "map_temp"
author: "Sai Shreyas Bhavanasi"
date: "11/2/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(ggplot2)
library(usmap)
library(ggthemes)
library(tibble)
library(viridis)
library(dplyr)
library(rgeos)
state <- map_data("state")
county <- map_data("county")
usa <- map_data("usa")
df = read.csv("data/vis_data/vis_dat.csv")

df = df %>% 
  filter(Lon > -150 & Lon < -50 & Lat > 20 & Lat< 50)
df = df[!is.na(df$D2_Hi),]
df = df[!is.na(df$Lat),]

library(mapproj)

df2 = data.frame(City = "MAPLE FALLS", State = "WA", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 49, Lon = -121.929)
df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 49, Lon = -95.34))
df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 48.380147429239486, Lon = -124.9))

df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 40.438564089182776, Lon = -124.40398315271037))

df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 40.43262875150735, Lon = -124.33235376063053))
#40.43262875150735, -124.33235376063053
# df = rbind(df,c)

df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 25.847255760595104, Lon = -97.38835720353877))
#25.847255760595104, -97.38835720353877

#47.42954034281501, -69.17932665630178
df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 47.42954034281501, Lon = -69.17932665630178))

#44.91469429949023, -67.00336321956611
df2 = rbind(df2,  data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 44.91469429949023, Lon = -67.00336321956611))

#45.30851220725746, -69.41196906976818
df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 45.30851220725746, Lon = -69.41196906976818))


#24.545979687846238, -81.8117847934193
df2 = rbind(df2,  data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 24.545979687846238, Lon = -81.8117847934193))

#34.574393505327905, -120.6099823317243
df2 = rbind(df2,  data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 34.574393505327905, Lon = -120.6099823317243))

#25.19597229396031, -80.3543262332071
df2 = rbind(df2, data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 25.19597229396031, Lon = -80.3543262332071))
```

```{r}
# library(rgeos)
# df = df[!is.na(df$Lat),]
# p1 = SpatialPoints(df[,c("Lat", "Lon")])
# p2 = SpatialPoints(data.frame(City = "WILLIAMS", State = "MN", date = date(), D0_Hi = 49, D0_Lo = 30, D1_Hi = 35, D1_Lo = 25, D2_Hi = 38, D2_Lo = 30, Lat = 25.19597229396031, Lon = -80.3543262332071)[,c("Lat", "Lon")])
# 
#  apply(gDistance(p1, p2, byid=TRUE), 1, which.min)
#  df[52,]
#  p2
 
```


```{r}
func <- function(df1, df2){
p1 = SpatialPoints(df1[,c("Lat", "Lon")])
p2 = SpatialPoints(df2[,c("Lat", "Lon")])
min_ind = apply(gDistance(p1, p2, byid=TRUE), 1, which.min)
df2[,4:9] = df1[min_ind, 4:9]
df2
}


for( i in 1:nrow(df2)){
  df = rbind(df, func(df, data.frame(df2[i,])))
}
```



```{r}

fld <- with(df, interp(x = Lon, y = Lat, z = D2_Hi))
df2 <- melt(fld$z, na.rm = TRUE)
names(df2) <- c("x", "y", "temp")
df2$Lon <- fld$x[df2$x]
df2$Lat <- fld$y[df2$y]
ggplot()+ 
    geom_point(data = df2, aes(y = Lat,x= Lon, colour = temp , stroke = 2))+

  # geom_map(data=county, map=county,
  #                   aes(long, lat, map_id=region),
  #                   color="#2b2b2b", fill=NA, size=0.1)+
  geom_map(data=state, map=state,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=0.2)+
    
  geom_map(data=usa, map=usa,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=.01)+
  coord_map("polyconic")+
  theme_minimal() +
  
  scale_color_viridis(option="magma")+ 
  labs(colour = "Temp") +
  theme(legend.position="right")

```


```{r}
#bottom half

library(raster)
usa <- map_data("usa")

pol1 = Polygon(usa[,c("long","lat")])
p1 <- SpatialPoints(usa[,c("long","lat")])

a = c(38, -70.58713866470633)
b = c(38, -124.73458425264569)
c = c(24.5, -124.73458425264569)
d = c(24.5, -72.58713866470633)

temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

library(rgeos)
p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gDifference(  gBuffer(p2, byid=TRUE, width=0),gBuffer(p1, byid=TRUE, width=0))
plot(res)
a=res@polygons
dat = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat)
dat2 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat2)
```

```{r}
# top left
usa <- map_data("usa")
pol1 = Polygon(usa[,c("long","lat")])
p1 <- SpatialPoints(usa[,c("long","lat")])

a = c(49.48709157805013, -126.0292411544105)
b = c(49.372767456697055, -97.20111573305981)
c = c(35.01791506999891, -96.9813892040004)
d = c(34.36753597096922, -124.97455433158129)
temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gDifference(  gBuffer(p2, byid=TRUE, width=0),gBuffer(p1, byid=TRUE, width=0))
plot(res)
a=res@polygons

dat2 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
# plot(dat2)

dat3 = as.data.frame(a[1][[1]]@Polygons[2][[1]]@coords)
plot(dat3)
```

```{r}
usa2 = usa[usa$order>4950 & usa$order<5050,]
ggplot()+
    geom_polygon(data = usa2, aes(x=usa2$long,y=usa2$lat), fill = "lightblue") 

# lake michigan
usa <- map_data("usa")

pol1 = Polygon(usa2[,c("long","lat")])
p1 <- SpatialPoints(usa2[,c("long","lat")])

a = c(44.19517160437166, -88.03181425992327)
b = c(44.17748599794071, -84.77623582388959)
c = c(41.056774105291225, -84.97354360789164)
d = c(41.1311228986116, -89.28965138293627)
temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gIntersection(  gBuffer(p1, byid=TRUE, width=0),gBuffer(p2, byid=TRUE, width=0))
# res <- gDifference(  gBuffer(p2, byid=T, width=0),gBuffer(p1, byid=T, width=0))
plot(res)
a=res@polygons

dat4 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat4)
# 41.63111,-87.34742	

```

```{r}
usa3 = usa[usa$order>4400 & usa$order<4750,]
ggplot()+
geom_map(data=usa, map=usa,
           aes(x=long,y= lat, map_id=region),
           color="black", fill="black", size=.1)+
    geom_polygon(data = usa3, aes(x=long,y=lat), fill = "lightblue") 

# lake erie


pol1 = Polygon(usa3[,c("long","lat")])
p1 <- SpatialPoints(usa3[,c("long","lat")])

a = c(43.528281172791125, -81.87143003643087)
b = c(43.723199406399075, -78.89256679347217)
c = c(41.411998034650495, -78.24462197355422)
d = c(41.39703243933011, -84.08310879021084)
temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gIntersection(  gBuffer(p1, byid=TRUE, width=0),gBuffer(p2, byid=TRUE, width=0))
# res <- gDifference(  gBuffer(p2, byid=T, width=0),gBuffer(p1, byid=T, width=0))
plot(res)
a=res@polygons

dat9 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat9)
# 41.63111,-87.34742	


```



```{r}
func2 <- function(a,b,c,d){
usa <- map_data("usa")

pol1 = Polygon(usa[,c("long","lat")])
p1 <- SpatialPoints(usa[,c("long","lat")])

# a = c(44.19517160437166, -88.03181425992327)
# b = c(44.17748599794071, -84.77623582388959)
# c = c(41.056774105291225, -84.97354360789164)
# d = c(41.1311228986116, -89.28965138293627)
temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gDifference(  gBuffer(p2, byid=TRUE, width=0),gBuffer(p1, byid=TRUE, width=0))
# res <- gDifference(  gBuffer(p2, byid=T, width=0),gBuffer(p1, byid=T, width=0))
plot(res)
a=res@polygons

dat4 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
# plot(dat4)
dat4
a
}
```

```{r}
# mroe michigan
a = c(49.8482220461071, -97.47405904039569)
b = c(49.08579769843062, -75.6525557263955)
c = c(40.84810428427789, -75.18327608523421)
d = c(41.6858225737601, -94.42374137284726)
a = func2(a,b,c,d)
dat5=as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)

```


```{r}
# NE
a = c(41.246257873632096, -79.64143297087567)
b = c(40.08947370526088, -68.25584014764978)
c = c(37.15714268482833, -68.78377974395625)
d = c(36.73521516453001, -83.39567010016603)
a = func2(a,b,c,d)
dat6=as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
# plot(dat6)
# dat8=as.data.frame(a[1][[1]]@Polygons[2][[1]]@coords)
# plot(dat8)

```


```{r}
a = c(49.32343518715469, -76.47379539303692)
b = c(49.67143801942952, -64.80046431914974)
c = c(38.27080937015975, -66.26696319777878)
d = c(40.40288869611612, -78.64421373340791)
a = func2(a,b,c,d)
dat7=as.data.frame(a[1][[1]]@Polygons[2][[1]]@coords)
plot(dat7)
dat12=as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat12)#candaian region
```

```{r}
a = c(43.21797785315606, -76.7594230482479)
b = c(40.94788604781764, -73.82577204501558)
c = c(48.70403470082143, -66.58205863585866)
d = c(45.03637007559224, -67.87033261211045)
a = func2(a,b,c,d)
dat10=as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat10)
```

```{r}
usa4 = usa[usa$region == "long island",]
ggplot()+
# geom_map(data=usa, map=usa,
#            aes(x=long,y= lat, map_id=region),
#            color="black", fill="black", size=.1)+
    geom_polygon(data = usa4, aes(x=long,y=lat), fill = "lightblue")

#ny


pol1 = Polygon(usa4[,c("long","lat")])
p1 <- SpatialPoints(usa4[,c("long","lat")])

a = c(41.001751527727585, -74.04773493362443)
b = c(41.143187833020214, -72.67103648349567)
c = c(40.08815292379516, -72.58119433974234)
d = c(40.46715040724515, -74.34632789397413)
temp = data.frame(x = c(a[2],b[2],c[2],d[2]), y = c(a[1],b[1],c[1],d[1]))
temp = rbind(temp,temp[1,])
pol2 = Polygon(temp[,c("x","y")])
p2 <- SpatialPoints(temp[,c("x","y")])

p1 <- SpatialPolygons(list(Polygons(list(pol1), "p1")))
p2 <- SpatialPolygons(list(Polygons(list(pol2), "p2")))
res <- gDifference(  gBuffer(p2, byid=TRUE, width=0),gBuffer(p1, byid=TRUE, width=0))
# res <- gDifference(  gBuffer(p2, byid=T, width=0),gBuffer(p1, byid=T, width=0))
plot(res)
a=res@polygons

dat11 = as.data.frame(a[1][[1]]@Polygons[1][[1]]@coords)
plot(dat11)
# 41.63111,-87.34742	

```


```{r}
can = map_data("world", c("canada"))
mex = map_data("world", c("mexico"))
state <- map_data("state")
county <- map_data("county")
usa <- map_data("usa")

library(ggplot2)
library(reshape2)
library(akima)
# prepare data in long format
fld <- with(df, interp(x = Lon, y = Lat, z = D2_Lo, jitter.random = T, extrap = T))
df2 <- melt(fld$z, na.rm = TRUE)
names(df2) <- c("x", "y", "temp")
df2$Lon <- fld$x[df2$x]
df2$Lat <- fld$y[df2$y]



mp = ggplot() +
  
 
    # geom_tile(data = df2, aes(x = Lon, y = Lat, fill = temp)) +
      geom_raster(data = df2, aes(x = Lon, y = Lat, fill = temp), interpolate = T) +

 geom_map(data=state, map=state,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=0.1)+ 
  geom_polygon(data = dat2, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat3, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat4, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat5, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat6, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat7, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat8, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat9, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat10, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat11, aes(x=x,y=y), fill = "lightblue") +
    geom_polygon(data = dat12, aes(x=x,y=y), fill = "lightblue") +

    geom_polygon(data = dat, aes(x=x,y=y), fill = "lightblue") +

    geom_map(data=can, map=can,
           aes(long, lat, map_id=region),
           color="black", fill="white", size=.1)+
  geom_map(data=mex, map=mex,
           aes(long, lat, map_id=region),
           color="black", fill="white", size=.1)+
   geom_map(data=usa, map=usa,
           aes(x=long,y= lat, map_id=region),
           color="black", fill=NA, size=.1)+
    scale_fill_continuous(name = "Temp (F)",low = "yellow", high = "red") +
  
    xlab("Longitude") +
  ylab("Latitude") +
  ylim(c(24,51))+
    xlim(c(-145,-50))+
  theme(panel.background = element_rect(fill = 'lightblue'),
            panel.grid.major = element_blank(), panel.grid = element_blank())
mp
ggsave(mp, file="map.pdf", width=8, height=4, unit = "in")

```

```{r}
library(ggplot2)
library(reshape2)
library(akima)
# prepare data in long format
fld <- with(df, interp(x = Lon, y = Lat, z = D2_Lo))
df2 <- melt(fld$z, na.rm = TRUE)
names(df2) <- c("x", "y", "temp")
df2$Lon <- fld$x[df2$x]
df2$Lat <- fld$y[df2$y]
state <- map_data("state")
county <- map_data("county")
usa <- map_data("usa")


ggplot() +
  geom_map(data=usa, map=usa,
           aes(long, lat, map_id=region),
           color="black", fill="white", size=.1)+
    geom_raster(data = df2, aes(x = Lon, y = Lat, z = temp), interpolate = T) +

  geom_map(data=state, map=state,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=0.1)+  # stat_contour() +
    scale_fill_continuous(name = "Temp (F)",low = "yellow", high = "red") +
    xlab("Longitude") +
  ylab("Latitude") +
  theme(panel.background = element_rect(fill = 'lightblue'),
            panel.grid.major = element_blank())


```

```{r}
```


```{r}
library(maps)
image(x=-90:-75, y = 25:40, z = outer(1:15, 1:15, "+"), 
      xlab = "lon", ylab = "lat")
map("state", add = TRUE)

library(grid)
outline <- map("usa", plot=FALSE) # returns a list of x/y coords
xrange <- range(outline$x, na.rm=TRUE) # get bounding box
yrange <- range(outline$y, na.rm=TRUE)
xbox <- xrange + c(-2, 2)
ybox <- yrange + c(-2, 2)
# create the grid path in the current device
polypath(c(outline$x, NA, c(xbox, rev(xbox))),
         c(outline$y, NA, rep(ybox, each=2)),
         col="light blue", rule="evenodd")
```

```{r}
library(raster)
dat <- data.frame(x = df$Lon, y = df$Lat, z = df$D2_Lo)
r <- raster(ncol=10, nrow=20)
r[] <- 1:ncell(r)
extent(r) <- extent(c(-20, 20, -20, 20))

r=disaggregate(r,10)
sp
r=mask(r,wrld_simpl)

#plotting
var_df <- as.data.frame(rasterToPoints(r))
```

```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(maps)
library(ggplot2)
library(reshape2)
library(akima)
# prepare data in long format
fld <- with(df, interp(x = Lon, y = Lat, z = D2_Lo))
df2 <- melt(fld$z, na.rm = TRUE)
names(df2) <- c("x", "y", "temp")
df2$Lon <- fld$x[df2$x]
df2$Lat <- fld$y[df2$y]

states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
world <- ne_countries(scale = "medium", returnclass = "sf")
usa <- subset(world, admin == "United States of America")
(alaska <- ggplot(data = world) +
     geom_sf(fill = "white") +
   theme(panel.background = element_rect(fill = 'lightblue'),
            panel.grid.major = element_blank(),
         panel.grid = element_blank())+

    plot.window(c(0,1),c(0,1), xaxs = "i", yaxs = "i")+
     coord_sf( xlim =c(  -139, -180), ylim = c(50,72), expand = FALSE,datum = NA))

(hawaii  <- ggplot(data = usa) +
     geom_sf(fill = "white") +
       theme(panel.background = element_rect(fill = 'lightblue'),
            panel.grid.major = element_blank(),
         panel.grid = element_blank())+
        plot.window(c(0,1),c(0,1), xaxs = "i", yaxs = "i")+
 theme_nothing() + 
    coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23)))

mainland <- ggplot() +
     geom_sf(data = world,fill = "white") +
         geom_raster(data = df2, aes(x = Lon, y = Lat, fill = temp), interpolate = T) +
      geom_sf(data = states, fill = NA) + 
     coord_sf(ylim = c(22,52), xlim =c(-150,-55))+
      scale_fill_continuous(name = "Temp (F)",low = "yellow", high = "red") +

   theme(panel.background = element_rect(fill = 'lightblue'),
            panel.grid.major = element_blank(), panel.grid = element_blank())

mainland +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -150,
      xmax = -130 ,
      ymin = 20,
      ymax = 35
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -130,
      xmax = -110,
      ymin = 20,
      ymax = 35
  )

```

```{r}
star <- c(25.000,1.000,31.000,18.000,49.000,18.000,35.000,29.000,40.000,46.000,
          25.000,36.000,10.000,46.000,15.000,29.000,1.000,18.000,19.000,18.000) %>% matrix(ncol=2, byrow=T) %>% apply(2, rev)
star <- rbind(star,star[1,])
rim  <- c(0,0, 50,0, 50,50,0,50,0,0) %>% matrix(ncol=2, byrow=T)

datapolyM <- rbind(rim,star) %>% as.data.frame()
names(datapolyM) <- c("x","y")
datapolyM$id <- "a"

ggplot(datapolyM, aes(x=x, y=y)) + 
  geom_polygon(fill="red")

datapolyM
```

```{r}
# library(raster)
# provinces <- getData(country="Canada", level=1)
state <- map_data("state")
county <- map_data("county")
usa <- map_data("usa")

ggplot()+ 
  # geom_map(data=county, map=county,
  #                   aes(long, lat, map_id=region),
  #                   color="#2b2b2b", fill=NA, size=0.1)+
  geom_map(data=state, map=state,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=0.2)+
  geom_map(data=usa, map=usa,
           aes(long, lat, map_id=region),
           color="black", fill=NA, size=.01)+
  theme_minimal() +
  geom_point(data = df, aes(y = Lat,x= Lon, colour = D2_Hi , stroke = 2))+
  scale_color_viridis(option="magma")+ 
  labs(colour = "Temp") +
  theme(legend.position="right")

```
